eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
server:
    port: 8084
spring:
    application:
        name: springcloud-zuul
zuul:
    routes:
        api-a:
            path: /api-a/**
            serviceId: springcloud-ribbon
        api-b:
            path: /api-b/**
            serviceId: springcloud-feign

